name: Generate MD Table
on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'

jobs:
  generate-table:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for proper git operations
          
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          
      - name: Run table generator
        run: go run main.go
        
      - name: Add commit count
        run: |
          COMMIT_COUNT=$(git rev-list --count HEAD)
          echo -e "\nTotal commits: ${COMMIT_COUNT} (Updated at $(date +'%Y-%m-%d %H:%M:%S UTC'))" >> README.md
        
      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git diff --quiet && git diff --staged --quiet || git commit -m "Auto-update markdown table and commit count"
          
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
